DROP TABLE OS_MANEUVER_LOGS CASCADE CONSTRAINTS;
DROP TABLE OS_SENSOR_READINGS CASCADE CONSTRAINTS;
DROP TABLE OS_CONJUNCTION_EVENTS CASCADE CONSTRAINTS;
DROP TABLE OS_ORBITAL_ELEMENTS CASCADE CONSTRAINTS;
DROP TABLE OS_DEBRIS_OBJECTS CASCADE CONSTRAINTS;
DROP TABLE OS_SATELLITES CASCADE CONSTRAINTS;
DROP TABLE OS_USERS CASCADE CONSTRAINTS;
