ALTER SESSION SET CURRENT_SCHEMA = ORBITSHIELD;

SELECT
    SATELLITE_ID,
    CODE,
    NAME,
    ORBIT_STATUS,
    FUEL_PERCENTAGE,
    SOLAR_ENERGY_PERCENTAGE
FROM OS_SATELLITES
ORDER BY CODE;

SELECT
    S.CODE AS SATELLITE_CODE,
    D.CODE AS DEBRIS_CODE,
    C.DISTANCE_KM,
    C.PROBABILITY,
    C.COLLISION_RISK,
    C.STATUS,
    C.DETECTED_AT
FROM OS_CONJUNCTION_EVENTS C
JOIN OS_SATELLITES S ON S.SATELLITE_ID = C.SATELLITE_ID
JOIN OS_DEBRIS_OBJECTS D ON D.DEBRIS_OBJECT_ID = C.DEBRIS_OBJECT_ID
WHERE C.COLLISION_RISK = 1
ORDER BY C.DETECTED_AT DESC;

SELECT
    S.CODE AS SATELLITE_CODE,
    R.TEMPERATURE_CELSIUS,
    R.RADIATION_LEVEL,
    R.BATTERY_VOLTAGE,
    R.SIMULATED_GRAVITY,
    R.SIMULATED_THRUST,
    R.CREATED_AT
FROM OS_SENSOR_READINGS R
JOIN OS_SATELLITES S ON S.SATELLITE_ID = R.SATELLITE_ID
WHERE S.CODE = 'ORB-01'
ORDER BY R.CREATED_AT DESC;

SELECT
    S.CODE AS SATELLITE_CODE,
    M.ACTION,
    M.SERVO_ANGLE,
    M.THRUST_LEVEL,
    M.SOURCE,
    M.EXECUTED_AT
FROM OS_MANEUVER_LOGS M
JOIN OS_SATELLITES S ON S.SATELLITE_ID = M.SATELLITE_ID
WHERE S.CODE = 'ORB-01'
ORDER BY M.EXECUTED_AT DESC;
